# Generated by Django 4.2.22 on 2025-07-02 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_meetingcache'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingBiliRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=32, verbose_name='会议id')),
                ('status', models.SmallIntegerField(choices=[(0, '初始化'), (1, '完成请求翻译'), (10, '已经上传完成')], default=0, verbose_name='上传状态')),
                ('replay_url', models.CharField(blank=True, max_length=128, null=True, verbose_name='回放会议url')),
            ],
            options={
                'verbose_name': 'meetings_records_bili',
                'verbose_name_plural': 'meetings_records_bili',
                'db_table': 'meetings_records_bili',
            },
        ),
        migrations.CreateModel(
            name='MeetingObsRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=32, verbose_name='会议id')),
                ('status', models.SmallIntegerField(choices=[(0, '初始化'), (1, '完成请求翻译'), (10, '已经上传完成')], default=0, verbose_name='上传状态')),
                ('text_vtt_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='文本vtt地址')),
                ('text_json_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='文本json地址')),
                ('text_video_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='文本video地址')),
            ],
            options={
                'verbose_name': 'meetings_records_obs',
                'verbose_name_plural': 'meetings_records_obs',
                'db_table': 'meetings_records_obs',
            },
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='replay_url',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='upload_status',
        ),
        migrations.AddField(
            model_name='meeting',
            name='bili_record',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meeting.meetingbilirecords'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='obs_records',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meeting.meetingobsrecords'),
        ),
    ]
