# Generated by Django 4.2.22 on 2025-07-25 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_meetingbilirecords_meetingobsrecords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingCycleDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=32, verbose_name='会议id')),
                ('start_date', models.CharField(max_length=32, verbose_name='会议开始日期')),
                ('end_date', models.CharField(max_length=32, verbose_name='会议结束日期')),
                ('start', models.CharField(max_length=32, verbose_name='会议开始时间')),
                ('end', models.CharField(max_length=32, verbose_name='会议结束时间')),
                ('cycle_type', models.SmallIntegerField(choices=[(0, 'Day'), (1, 'Week'), (2, 'Month')], verbose_name='周期类型')),
                ('interval', models.IntegerField(verbose_name='子会议时间间隔')),
                ('point', models.IntegerField(verbose_name='周期内的会员召开时间')),
            ],
            options={
                'verbose_name': 'meetings_cycle_date',
                'verbose_name_plural': 'meetings_cycle_date',
                'db_table': 'meetings_cycle_date',
            },
        ),
        migrations.CreateModel(
            name='MeetingCycleSubMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=32, verbose_name='会议id')),
                ('sub_id', models.CharField(max_length=32, verbose_name='子会议的ID')),
                ('date', models.CharField(max_length=32, verbose_name='会议日期')),
                ('start', models.CharField(max_length=32, verbose_name='会议开始时间')),
                ('end', models.CharField(max_length=32, verbose_name='会议结束时间')),
            ],
            options={
                'verbose_name': 'meetings_cycle_sub_meeting',
                'verbose_name_plural': 'meetings_cycle_sub_meeting',
                'db_table': 'meetings_cycle_sub_meeting',
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_cycle',
            field=models.BooleanField(default=False, verbose_name='是否周期性会议'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='cycle_date',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meeting.meetingcycledate'),
        ),
    ]
