# Generated by Django 4.2.23 on 2025-08-08 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0005_meetingcycledate_meetingcyclesubmeeting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='bili_records',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meeting.meetingbilirecords'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='cycle_date',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meeting.meetingcycledate'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='obs_records',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meeting.meetingobsrecords'),
        ),
        migrations.AlterField(
            model_name='meetingcycledate',
            name='point',
            field=models.IntegerField(blank=True, null=True, verbose_name='周期内的会员召开时间'),
        ),
    ]
