# Generated by Django 4.2.23 on 2025-08-14 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0006_alter_meeting_bili_records_alter_meeting_cycle_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingcycledate',
            name='meeting',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cycle_date', to='meeting.meeting'),
        ),
        migrations.AddField(
            model_name='meetingcyclesubmeeting',
            name='meeting',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cycle_sub_meeting', to='meeting.meeting'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='会议日期'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='end',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='会议结束时间'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='会议开始时间'),
        ),
        migrations.AlterField(
            model_name='meetingcycledate',
            name='interval',
            field=models.IntegerField(blank=True, null=True, verbose_name='子会议时间间隔'),
        ),
        migrations.AlterField(
            model_name='meetingcycledate',
            name='point',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='周期内的会员召开时间'),
        ),
    ]
